# Generated by Django 3.2.7 on 2021-09-25 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50, null=True)),
                ('university_roll_no', models.IntegerField(null=True)),
                ('course', models.CharField(choices=[('B.Sc. (H) Botany', 'B.Sc. (H) Botany'), ('B.Sc. (H) Chemistry', 'B.Sc. (H) Chemistry'), ('B.Sc. (H) Computer Science', 'B.Sc. (H) Computer Science'), ('B.Sc. (H) Electronics', 'B.Sc. (H) Electronics'), ('B.Sc. (H) Mathematics', 'B.Sc. (H) Mathematics'), ('B.Sc. (H) Physics', 'B.Sc. (H) Physics'), ('B.Sc. (H) Zoology', 'B.Sc. (H) Zoology'), ('B.Com. (H)', 'B.Com. (H)'), ('B.A. (H) Economics', 'B.A. (H) Economics'), ('B.A. (H) English', 'B.A. (H) English'), ('B.A. (H) Hindi', 'B.A. (H) Hindi'), ('B.A. (H) History', 'B.A. (H) History'), ('B.A. (H) Philosophy', 'B.A. (H) Philosophy'), ('B.A. (H) Physical Education', 'B.A. (H) Physical Education'), ('B.A. (H) Sanskrit', 'B.A. (H) Sanskrit')], max_length=100, null=True)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(to='faculty.SubjectDetail')),
            ],
        ),
    ]
