# Generated by Django 3.2.7 on 2021-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='university_roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
