# Generated by Django 3.2.7 on 2021-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='subject',
            field=models.ManyToManyField(to='faculty.Subject'),
        ),
    ]
