# Generated by Django 3.2.7 on 2021-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentdetail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='university_roll_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
