# Generated by Django 3.2.7 on 2021-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentdetail_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='course',
            field=models.CharField(choices=[('B.Com. (H)', 'B.Com. (H)'), ('B.Sc. (H) Botany', 'B.Sc. (H) Botany'), ('B.Sc. (H) Chemistry', 'B.Sc. (H) Chemistry'), ('B.Sc. (H) Computer Science', 'B.Sc. (H) Computer Science'), ('B.Sc. (H) Electronics', 'B.Sc. (H) Electronics'), ('B.Sc. (H) Mathematics', 'B.Sc. (H) Mathematics'), ('B.Sc. (H) Physics', 'B.Sc. (H) Physics'), ('B.Sc. (H) Zoology', 'B.Sc. (H) Zoology'), ('B.A. (H) Economics', 'B.A. (H) Economics'), ('B.A. (H) English', 'B.A. (H) English'), ('B.A. (H) Hindi', 'B.A. (H) Hindi'), ('B.A. (H) History', 'B.A. (H) History'), ('B.A. (H) Philosophy', 'B.A. (H) Philosophy'), ('B.A. (H) Physical Education', 'B.A. (H) Physical Education'), ('B.A. (H) Sanskrit', 'B.A. (H) Sanskrit')], max_length=200),
        ),
    ]
