# Generated by Django 3.2.7 on 2021-09-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0003_alter_facultydetail_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetail',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
