# Generated by Django 3.2.7 on 2021-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210908_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'TEACHER'), (2, 'STUDENT')], default=2),
        ),
    ]
