# Generated by Django 3.2.7 on 2021-09-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time3', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time4', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time5', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time6', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time7', to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time8', to='faculty.subject'),
        ),
    ]
