# Generated by Django 3.2.7 on 2021-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='a1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='a9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='i1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='i2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='i3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='practical',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='a9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='i1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='i2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='i3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='practical',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks_out_of',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
