# Generated by Django 3.2.7 on 2021-09-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Out_Of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField(null=True)),
                ('m2', models.IntegerField(null=True)),
                ('m3', models.IntegerField(null=True)),
                ('m4', models.IntegerField(null=True)),
                ('m5', models.IntegerField(null=True)),
                ('m6', models.IntegerField(null=True)),
                ('m7', models.IntegerField(null=True)),
                ('m8', models.IntegerField(null=True)),
                ('m9', models.IntegerField(null=True)),
                ('m10', models.IntegerField(null=True)),
                ('m11', models.IntegerField(null=True)),
                ('m12', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subjectdetail')),
            ],
            options={
                'db_table': 'Attendance_Out_Of',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField(null=True)),
                ('m2', models.IntegerField(null=True)),
                ('m3', models.IntegerField(null=True)),
                ('m4', models.IntegerField(null=True)),
                ('m5', models.IntegerField(null=True)),
                ('m6', models.IntegerField(null=True)),
                ('m7', models.IntegerField(null=True)),
                ('m8', models.IntegerField(null=True)),
                ('m9', models.IntegerField(null=True)),
                ('m10', models.IntegerField(null=True)),
                ('m11', models.IntegerField(null=True)),
                ('m12', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subjectdetail')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
