# Generated by Django 3.2.7 on 2021-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='m1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m11',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='m9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m11',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='m9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_out_of',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
